# Generated by Django 4.1 on 2023-11-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='voting.question')),
            ],
        ),
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='questions',
            field=models.ManyToManyField(related_name='voting', through='voting.VotingQuestion', to='voting.question'),
        ),
        migrations.AddField(
            model_name='votingquestion',
            name='voting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.voting'),
        ),
    ]
