# Generated by Django 4.1 on 2023-11-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_votingquestion_remove_voting_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingquestion',
            old_name='voting_id',
            new_name='voting',
        ),
    ]
