# Generated by Django 4.1 on 2023-11-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_rename_voting_id_votingquestion_voting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingquestion',
            old_name='question_id',
            new_name='question',
        ),
    ]
